
name: CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Git Client
        run: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          git config --global user.email "github-actions@doesnotmatter.dev"
          git config --global user.name "GitHub Actions"

      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2

      - name: List Directory
        run: |
          ls -la ./ 

      - name: Pushes to deploy
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'deploy'
          destination-github-username: 'asysteco'
          destination-repository-name: 'slimSysteco'
          user-email: alvaromelkunas9@gmail.com
          target-branch: deploy
