
name: CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Git Client
        run: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          git config --global user.email "github-actions@doesnotmatter.dev"
          git config --global user.name "GitHub Actions"

      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Install Composer
        run: |
          sh ./deploy.sh
