
name: CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Git Client
        run: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          git config --global user.email "github-actions@doesnotmatter.dev"
          git config --global user.name "GitHub Actions"

      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: debug-output
          path: output.log

      - name: Collect artifacts
        run: |
          ls ./
          cat output.log
      - name: Push artifacts
        run: |
          git clone --depth 1 --single-branch -b deploy git@github.com:asysteco/slimSysteco.git deploy
          mv deploy/.git deploy-.git
          rm -rf deploy
          mkdir deploy
          mv deploy-.git deploy/.git
          cd deploy
          cp -R ../dist/* .
          git add .
          git diff --staged --quiet || git commit -m "Update Artifacts"
          git push
