
name: CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@master
        with:
          php_version: 7.4
          ssh_key: ${{ secrets.PRIV_SECRET }}
          ssh_key_pub: ${{ secrets.PUB_SECRET }}

      - uses: actions/upload-artifact@v2
        with:
          name: debug-output
          path: output.log

      - name: Collect artifacts
        run: |
          mkdir dist
          cp out/*.pdf dist/
      - name: Push artifacts
        run: |
          git clone --depth 1 --single-branch -b deploy git@github.com:asysteco/slimSysteco.git deploy
          mv deploy/.git deploy-.git
          rm -rf deploy
          mkdir deploy
          mv deploy-.git deploy/.git
          cd deploy
          cp -R ../dist/* .
          git add .
          git diff --staged --quiet || git commit -m "Update Artifacts"
          git push
