
name: CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@master
        with:
          php_version: 8.0
          ssh_key: ${{ secrets.PRIV_SECRET }}
          ssh_key_pub: ${{ secrets.PUB_SECRET }}

      - uses: actions/upload-artifact@v2
        with:
          name: debug-output
          path: output.log
